### ISSUE TITLE
Does not compile on IDE 1.8.13

### ISSUE THREAD

**Issue by noeldum** [mgrl/0816-feeder-firmware#3]
I am trying to compile it for IDE 1.8.13.

1/ On open the IDE ask to have the sketch inside a folder of its own name. After accepting we have to move all other files inside that newly created folder.

2/ On compile it comes up with arduino.h not found. Commenting the #include arduino.h does the trick.

3/ Then comes the error uint8_t does not name a type. Adding #include <stdint.h>  inside config.h seems to get going.

4/ Then comes 'A11' was not declared in this scope. Replaced A11 to A14 with 65 to 68.

compile works after that. Not sure this is functional though.

It's a good project. Is anyone still maintaining it?

**Comment by noeldum** [comment]
looks like this was probably not meant to be compiled in arduino IDE. The readme does not say.

I have made the change to compile for arduino IDE in my own fork.
noeldum/0816-feeder-firmware

I plan to add improvements to the code. In particular controlling the speed of the advance action for jumpy parts that get off the tape before picking. Also the ability to send a feed command while disabled.
